import type { InvestigationSession, SessionReport, TimelineEntry, FrequencyActivity } from '@/types';

export function formatDuration(ms: number): string {
  const s = Math.floor(ms / 1000);
  const m = Math.floor(s / 60);
  const h = Math.floor(m / 60);
  if (h > 0) return `${h}h ${m % 60}m ${s % 60}s`;
  if (m > 0) return `${m}m ${s % 60}s`;
  return `${s}s`;
}

export function formatTime(ts: number): string {
  return new Date(ts).toLocaleString('en-US', {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit', second: '2-digit',
  });
}

export function formatSessionTime(ms: number): string {
  const s = Math.floor(ms / 1000);
  const m = Math.floor(s / 60);
  return `${String(m).padStart(2, '0')}:${String(s % 60).padStart(2, '0')}`;
}

export function generateReport(session: InvestigationSession): SessionReport {
  const timeline: TimelineEntry[] = session.events.map((e) => ({
    time: e.sessionTime,
    event: `[${session.band} ${e.frequency}${session.band === 'FM' ? ' MHz' : ' kHz'}] ${e.description}`,
    significance:
      e.signalStrength > 70 ? 'high' : e.signalStrength > 40 ? 'medium' : 'low',
  }));

  const freqMap = new Map<number, FrequencyActivity>();
  session.events.forEach((e) => {
    const existing = freqMap.get(e.frequency) ?? {
      frequency: e.frequency,
      hits: 0,
      anomalies: 0,
      peakStrength: 0,
    };
    existing.hits++;
    if (e.type !== 'marker') existing.anomalies++;
    existing.peakStrength = Math.max(existing.peakStrength, e.signalStrength);
    freqMap.set(e.frequency, existing);
  });

  const frequencyActivity = Array.from(freqMap.values()).sort(
    (a, b) => b.anomalies - a.anomalies
  );

  const summary = `Investigation session logged ${session.events.length} events over ${formatDuration(session.duration)}. Peak signal strength recorded: ${session.peakSignalStrength.toFixed(1)}%. Band: ${session.band}.`;

  const conclusion = session.totalAnomalies > 5
    ? 'Multiple audio anomalies were detected during this session. Further analysis is recommended.'
    : session.totalAnomalies > 0
      ? 'A small number of audio anomalies were recorded. Results are inconclusive.'
      : 'No significant anomalies were detected during this session.';

  return { session, summary, timeline, frequencyActivity, conclusion };
}

export function exportAsJSON(session: InvestigationSession): void {
  const report = generateReport(session);
  const data = JSON.stringify({ ...report, exportedAt: new Date().toISOString() }, null, 2);
  downloadFile(data, `mamz-spirit-box-${session.id}.json`, 'application/json');
}

export function exportAsTXT(session: InvestigationSession): void {
  const report = generateReport(session);
  const lines = [
    '=====================================',
    '  MAMZ SPIRIT BOX — INVESTIGATION REPORT',
    '=====================================',
    '',
    `Session ID:     ${session.id}`,
    `Start Time:     ${formatTime(session.startTime)}`,
    `End Time:       ${session.endTime ? formatTime(session.endTime) : 'Active'}`,
    `Duration:       ${formatDuration(session.duration)}`,
    `Band:           ${session.band}`,
    `Location:       ${session.location ?? 'Not specified'}`,
    '',
    '--- SUMMARY ---',
    report.summary,
    '',
    '--- TIMELINE ---',
    ...report.timeline.map(
      (t) => `[${formatSessionTime(t.time)}] [${t.significance.toUpperCase()}] ${t.event}`
    ),
    '',
    '--- FREQUENCY ACTIVITY ---',
    ...report.frequencyActivity.map(
      (f) =>
        `${f.frequency}${session.band === 'FM' ? ' MHz' : ' kHz'} — Hits: ${f.hits}, Anomalies: ${f.anomalies}, Peak: ${f.peakStrength.toFixed(1)}%`
    ),
    '',
    '--- CONCLUSION ---',
    report.conclusion,
    '',
    '=====================================',
    'Generated by Mamz Spirit Box',
    'Created by Mamad Shirali | t.me/Mamd_shirali',
    '=====================================',
  ];
  downloadFile(lines.join('\n'), `mamz-spirit-box-${session.id}.txt`, 'text/plain');
}

function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
